### ISSUE TITLE
Menu not showing Board options

### ISSUE THREAD

**Issue by hemalchevli** [gepd/Stino#20]
![untitled](https://cloud.githubusercontent.com/assets/948576/12611153/50146794-c511-11e5-8d9c-1f6730b4bf51.png)

Here is the console output when I select the arduino application folder.

Traceback (most recent call last):
  File ".\StinoStarter.py", line 470, in on_done
  File ".\app\base.py", line 24, in refresh
  File ".\app\base.py", line 53, in genKeywordList
  File ".\app\base.py", line 884, in getKeywordListFromPlatform
  File ".\app\base.py", line 866, in getKeywordListFromCoreFolderList
  File ".\app\base.py", line 855, in getKeywordListFromFile
UnboundLocalError: local variable 'keyword_type' referenced before assignment

**Comment by gepd** [comment]
You have installed an old branch of Stino, I didn't used it so I can't help you. But I'm working in a new plugin it's not using the arduino IDE instead use [platformIO](http://platformio.org/) as compiler, it currently is in beta, if you like to try it and maybe report any error/bug or new feature, you will be welcome.

All the details about the project here:
https://github.com/gepd/Deviot
